# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempinfo',
            name='awaz',
            field=models.FileField(default=0, upload_to='sitatic/audio', verbose_name='awaz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempinfo',
            name='fanyi',
            field=models.CharField(max_length=40, verbose_name='\u7ffb\u8bd1'),
        ),
        migrations.AlterField(
            model_name='tempinfo',
            name='font',
            field=models.CharField(max_length=20, verbose_name='\u62fc\u97f3'),
        ),
        migrations.AlterField(
            model_name='tempinfo',
            name='juzi',
            field=models.CharField(max_length=100, verbose_name='\u53e5\u5b50'),
        ),
    ]
