# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0002_auto_20180806_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinfo',
            name='awaz',
            field=models.FileField(upload_to='static/admin/audio', verbose_name='awaz'),
        ),
    ]
