# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0004_auto_20180806_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempinfo',
            name='awaz',
        ),
        migrations.AddField(
            model_name='tempinfo',
            name='ph',
            field=models.ImageField(max_length=200, null=True, upload_to='uploadImages', verbose_name='rasim'),
        ),
    ]
