# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0008_auto_20180807_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempinfo',
            name='ph',
        ),
        migrations.AlterField(
            model_name='tempinfo',
            name='fanyi',
            field=models.TextField(max_length=40, verbose_name='\u7ffb\u8bd1'),
        ),
        migrations.AlterField(
            model_name='tempinfo',
            name='juzi',
            field=models.TextField(max_length=100, verbose_name='\u53e5\u5b50'),
        ),
    ]
