# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0010_tempinfo_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempinfo',
            name='duyin',
            field=models.CharField(default=0, max_length=100, verbose_name='ukulux'),
            preserve_default=False,
        ),
    ]
