# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-11 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0011_tempinfo_duyin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempinfo',
            name='ph',
        ),
    ]
