# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-11 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guoyu', '0012_remove_tempinfo_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempinfo',
            name='duyin',
        ),
    ]
